/* ns__file unit: static-command, comp: chase.ts */
/*
* This file is autogenerated using the easy-oclif-cli template with ns-flip. Please view
* the instructions for this code base at meta/instructions.md.
*/

/* ns__start_section imports */
import {Command, flags} from '@oclif/command'

/* ns__custom_start customImports */
/* ns__custom_end customImports */
/* ns__end_section imports */

export default class Chase extends Command {
static description = `compare generated code to your model, changing both until you've replicated the model with your template
`

static examples = [
/* ns__custom_start examples */
// replace this when you change your command!! To regenerate fresh, first delete everything between the squre brackets.
  `$ copykat chase sampleTemplateDir 
You have executed the chase command...
`,
/* ns__custom_end examples */
]

static flags = {
  help: flags.help({char: 'h'}),
}

static args = [
  {
    name: 'templateDir',
    description: 'the path to your template',
    required: true,
  },
]

async run() {
  const {args} = this.parse(Chase)

  const {templateDir} = args
  /* ns__custom_start run */
  // Put your custom code here...
  Object.keys(args).map((argName: string) => {
    if (args[argName] === 'sampleBadArgValue')
      throw new Error(`bad arg value '${args[argName]}' for arg '${argName}'`)
    return argName
  })
  this.log(`You have executed the chase command.
  Here are the args you used: 
    templateDir: ${templateDir}
Learn how to modify the generated code here: https://ns-flip.nostack.net/Safe-Custom-Code.`)
  /* ns__custom_end run */
}
}
